[package]
name = "rpi-munin-bme280"
version = "0.1.0"
authors = ["sam-tk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bme280 = "^0.2"
linux-embedded-hal = "^0"
simple-munin-plugin = "^0"
